# Generated by Django 4.1.4 on 2022-12-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
    ]
